syntax = "proto3";

package request_handler;

import "mini_vllm_proto/model_runner.proto";

service RequestHandlerService {
  rpc GenerateText(.request_handler.GenerateText) returns (stream .request_handler.GenerateTextEvent);
}

message GenerateText {
  string prompt = 1;
  uint64 max_new_tokens = 2;
  float repeat_penalty = 3;
  uint64 repeat_last_n = 4;
  bool stream_output = 5;
}

message GenerateTextEvent {
  oneof event {
    string text = 1;
    model_runner.TextGenerationStats stats = 2;
  }
}
